CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_EXT_POWER=n
CONFIG_ZMK_STUDIO=n   # 如果存在这行
CONFIG_BOARD_ENABLE_DCDC_HV=n 
# 减少连接参数更新失败后的重试次数和等待时间
CONFIG_BT_CONNECTION_PARAMETERS_UPDATE_TIMEOUT=1000
CONFIG_BT_CONNECTION_PARAMETERS_UPDATE_RETRIES=1
