CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_SLEEP_TIMEOUT=1800000
CONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
CONFIG_ZMK_EXT_POWER=n
CONFIG_ZMK_STUDIO=n   # 如果存在这行
CONFIG_BOARD_ENABLE_DCDC_HV=n 
# 蓝牙连接参数：让从机在连接建立后更快完成参数协商，以减少空闲时的不必要通信
CONFIG_BT_CONN_PARAM_UPDATE_TIMEOUT=1000
CONFIG_BT_CONN_PARAM_UPDATE_RETRIES=1
